# Generated by Django 4.1.5 on 2024-04-12 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_mail_id', models.EmailField(max_length=254)),
                ('user_mobile_number', models.CharField(max_length=12, null=True)),
                ('user_feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resume')),
                ('name', models.CharField(max_length=50, null=True)),
                ('insta_id', models.CharField(max_length=400, null=True)),
                ('whatspp_num', models.CharField(max_length=12, null=True)),
                ('linkedin_id', models.CharField(max_length=400, null=True)),
                ('github_id', models.CharField(max_length=400, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('discription', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('link', models.CharField(default='https://github.com/GuruRaj0305', max_length=400)),
            ],
        ),
    ]
